//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capitulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capitulo()
        {
            this.Comentario = new HashSet<Comentario>();
            this.DenunciaCapitulo = new HashSet<DenunciaCapitulo>();
        }
    
        public int IdCapitulo { get; set; }
        public string Titulo { get; set; }
        public string Conteudo { get; set; }
        public bool Situacao { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioAlteraStatus { get; set; }
        public int IdHistoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciaCapitulo> DenunciaCapitulo { get; set; }
        public virtual Historia Historia { get; set; }
    }
}
