//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comentario()
        {
            this.DenunciaComentario = new HashSet<DenunciaComentario>();
        }
    
        public int IdComentario { get; set; }
        public string Conteudo { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioAlteraStatus { get; set; }
        public int IdUsuario { get; set; }
        public int IdCapitulo { get; set; }
    
        public virtual Capitulo Capitulo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciaComentario> DenunciaComentario { get; set; }
    }
}
