//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competicao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competicao()
        {
            this.Inscricao = new HashSet<Inscricao>();
            this.DenunciaCompeticao = new HashSet<DenunciaCompeticao>();
        }
    
        public int IdCompeticao { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInicioInscri { get; set; }
        public System.DateTime DataFimInscri { get; set; }
        public System.DateTime DataInicioVota { get; set; }
        public System.DateTime DataFimVota { get; set; }
        public int PontoExperiencia { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioAlteraStatus { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> Vencedora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscricao> Inscricao { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciaCompeticao> DenunciaCompeticao { get; set; }
    }
}
