//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoLiterario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventoLiterario()
        {
            this.DenunciaEvento = new HashSet<DenunciaEvento>();
        }
    
        public int IdEvento { get; set; }
        public string Nome { get; set; }
        public byte[] Imagem { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioAlteraStatus { get; set; }
        public string Link { get; set; }
        public int IdUsuario { get; set; }
        public int IdLocalizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciaEvento> DenunciaEvento { get; set; }
        public virtual Localizacao Localizacao { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
