//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historia()
        {
            this.Capitulo = new HashSet<Capitulo>();
            this.DenunciaHistoria = new HashSet<DenunciaHistoria>();
            this.Favorito = new HashSet<Favorito>();
            this.Inscricao = new HashSet<Inscricao>();
            this.ListaLeitura = new HashSet<ListaLeitura>();
        }
    
        public int IdHistoria { get; set; }
        public string Titulo { get; set; }
        public byte[] Capa { get; set; }
        public string Sinopse { get; set; }
        public string Classificacao { get; set; }
        public int QtdFavoritos { get; set; }
        public bool Situacao { get; set; }
        public int QtdVisualizacoes { get; set; }
        public string Status { get; set; }
        public Nullable<int> UsuarioAlteraStatus { get; set; }
        public int IdUsuario { get; set; }
        public int IdIdioma { get; set; }
        public int IdGenero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capitulo> Capitulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DenunciaHistoria> DenunciaHistoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorito> Favorito { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscricao> Inscricao { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaLeitura> ListaLeitura { get; set; }
    }
}
