//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeepWritingBDEntities : DbContext
    {
        public KeepWritingBDEntities()
            : base("name=KeepWritingBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capitulo> Capitulo { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Competicao> Competicao { get; set; }
        public virtual DbSet<Denuncia> Denuncia { get; set; }
        public virtual DbSet<DenunciaCapitulo> DenunciaCapitulo { get; set; }
        public virtual DbSet<DenunciaComentario> DenunciaComentario { get; set; }
        public virtual DbSet<DenunciaCompeticao> DenunciaCompeticao { get; set; }
        public virtual DbSet<DenunciaEvento> DenunciaEvento { get; set; }
        public virtual DbSet<DenunciaHistoria> DenunciaHistoria { get; set; }
        public virtual DbSet<DenunciaUsuario> DenunciaUsuario { get; set; }
        public virtual DbSet<EventoLiterario> EventoLiterario { get; set; }
        public virtual DbSet<Favorito> Favorito { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Inscricao> Inscricao { get; set; }
        public virtual DbSet<Localizacao> Localizacao { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<PontoExperiencia> PontoExperiencia { get; set; }
        public virtual DbSet<Historia> Historia { get; set; }
        public virtual DbSet<ListaLeitura> ListaLeitura { get; set; }
        public virtual DbSet<Voto> Voto { get; set; }
    }
}
