//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeepWriting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontoExperiencia
    {
        public int IdPontoExperiencia { get; set; }
        public string Acao { get; set; }
        public int QtdPonto { get; set; }
    }
}
